name = "Extremely Optimised"
author = "LittleChest"
version = "_VERSION_"
description = "Improve your Minecraft experience with the ultimate in optimisation and without any QoL features!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.15.10"
minecraft = "1.20.5-pre1"

[options]
no-internal-hashes = true
