name = "Titanium Optimized"
author = "LittleChest"
version = "20.6.1"
description = "Improve your Minecraft experience with extreme performance and lots of bug fixes without any QoL features!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.15.10"
minecraft = "1.20.6"

[options]
no-internal-hashes = true
